name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish linux-x64
      run: dotnet publish -r linux-x64 -c Release -o build/linux-x64 -p:PublishSingleFile=true && gzip build/linux-x64/code0k-cc
    - name: Upload linux-x64
      uses: actions/upload-artifact@v1
      with:
        name: linux-x64
        path: build/linux-x64/code0k-cc.gz
    - name: Publish win-x64
      run: dotnet publish -r win-x64 -c Release -o build/win-x64 -p:PublishSingleFile=true && gzip build/win-x64/code0k-cc
    - name: Upload win-x64
      uses: actions/upload-artifact@v1
      with:
        name: win-x64
        path: build/win-x64/code0k-cc.gz
    - name: Publish osx-x64
      run: dotnet publish -r osx-x64 -c Release -o build/osx-x64 -p:PublishSingleFile=true && gzip build/osx-x64/code0k-cc
    - name: Upload osx-x64
      uses: actions/upload-artifact@v1
      with:
        name: osx-x64
        path: build/osx-x64/code0k-cc.gz
